# Generated by Django 2.0.6 on 2018-10-19 20:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.TextField(max_length=1000)),
                ('date_Submitted', models.DateTimeField(default=datetime.datetime.now)),
                ('deposits', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('withdraws', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('emergency_fund', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
