# Generated by Django 2.0.6 on 2018-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_auto_20181019_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=257)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
