# Generated by Django 2.0.6 on 2018-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_usersetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetup',
            name='name',
        ),
        migrations.AddField(
            model_name='usersetup',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersetup',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
