# Generated by Django 2.0.6 on 2018-10-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_auto_20181022_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetup',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
