# Generated by Django 2.0.6 on 2018-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0005_auto_20181022_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('withdraws', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='deposits',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='withdraws',
        ),
    ]
