# Generated by Django 2.0.6 on 2018-10-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0007_auto_20181022_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
