# Generated by Django 2.0.6 on 2018-10-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0008_transactionmodel_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='username',
        ),
    ]
