# Generated by Django 2.0.6 on 2018-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0010_auto_20181023_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='deposits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='withdraws',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
