# Generated by Django 2.0.6 on 2018-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0014_auto_20181026_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
