# Generated by Django 2.0.6 on 2018-10-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0015_auto_20181026_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='expenses',
        ),
    ]
