# Generated by Django 2.0.6 on 2018-10-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0016_remove_expensemodel_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='emergency_fund',
            field=models.FloatField(default=0),
        ),
    ]
