# Generated by Django 2.0.6 on 2018-10-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0017_auto_20181029_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetup',
            name='nameFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExpenseApp.ExpenseModel'),
        ),
    ]
