# Generated by Django 2.0.6 on 2018-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0018_usersetup_namefk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
