# Generated by Django 2.0.6 on 2018-10-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0020_auto_20181029_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='reason',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
